name: Basic pipeline
run-name: ${{ github.actor }} is pushed another piece of shitty code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    working-directory: /home/runner/work/text-editor/frontend
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - run: echo " дагестанские москвичи продакшн "
      - run: echo " в ролях "
      - run: echo " самый богатый человек кирова "
      - run: echo " артем ресторанович "
      - run: echo " алексей симпович "
      - run: echo " дмитрий шузыотдиси "
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build
        run: npm run build
      - name: lint
        run: npm run lint
